### ISSUE TITLE
Sidecar support ?

### ISSUE THREAD

**Issue by didier-segura** [mziyabo/argocd-trivy-extension#3]
From what I can see in ArgoCD, the extension can't display all the vulnerability report of a "complex" statefulset or deployment.

If we have only one container, by example solr, the Vulnerability report is the good one (we have only one VulnerabilityReport in the namespace), but if we have multiple sidecars in a statefulset, the extension only show one container (in my case the sidecar, not the "main" container).

Is it possible to add the ability to select in the vulnerability tab the container we want (main container, initContainer, sidecar container ?) and filter on them ?

Best regards.

**Comment by mziyabo** [comment]
Thanks @didier-segura. More or less baked in the container limitation in how the vulnerability report URL is constructed.
It's on my radar and I'll get a fix out as soon as I can.

**Comment by didier-segura** [comment]
To mitigate this issue, you can order in your Helm chart your containers. 

If the first one is the "main" container, at this time it can be a "workaround" ;)

`https://github.com/mziyabo/argocd-trivy-extension/blob/main/src/index.js#L11`

**Comment by mziyabo** [comment]
@didier-segura @jgalais Enhancement/fix for this has been shipped with the `0.2.0` release.

Added a dropdown for the pod containers so you can switch between the reports:

<img width="1379" alt="Screenshot 2024-04-13 at 15 04 51" src="https://github.com/mziyabo/argocd-trivy-extension/assets/7566137/fe80ad31-ddbf-4057-97dd-062b8ea58e80">
